# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 17) do

  create_table "backup_entries", :id => false, :force => true do |t|
    t.column "backupId",    :string,  :limit => 12, :default => "", :null => false
    t.column "year",        :string,  :limit => 10
    t.column "semester",    :string,  :limit => 3
    t.column "version",     :string,  :limit => 5
    t.column "currentflag", :integer, :limit => 10, :default => 0,  :null => false
    t.column "staff",       :integer, :limit => 10, :default => 0,  :null => false
    t.column "venue",       :integer, :limit => 10, :default => 0,  :null => false
  end

  create_table "bdrb_job_queues", :force => true do |t|
    t.column "args",           :binary
    t.column "worker_name",    :string
    t.column "worker_method",  :string
    t.column "job_key",        :string
    t.column "taken",          :integer
    t.column "finished",       :integer
    t.column "timeout",        :integer
    t.column "priority",       :integer
    t.column "submitted_at",   :datetime
    t.column "started_at",     :datetime
    t.column "finished_at",    :datetime
    t.column "archived_at",    :datetime
    t.column "tag",            :string
    t.column "submitter_info", :string
    t.column "runner_info",    :string
    t.column "worker_key",     :string
    t.column "scheduled_at",   :datetime
  end

  create_table "clash_exceptions", :id => false, :force => true do |t|
    t.column "clashListId",   :integer,                               :null => false
    t.column "clashListName", :string,  :limit => 30, :default => "", :null => false
    t.column "subjectCode",   :string,  :limit => 10, :default => "", :null => false
  end

  add_index "clash_exceptions", ["subjectCode"], :name => "subjectCode"

  create_table "lesson_groups", :id => false, :force => true do |t|
    t.column "groupId",     :integer,                               :null => false
    t.column "groupIndex",  :string,  :limit => 10, :default => "", :null => false
    t.column "groupPrefix", :string,  :limit => 5,  :default => "", :null => false
    t.column "groupNo",     :integer, :limit => 2,                  :null => false
    t.column "groupSize",   :integer, :limit => 3,                  :null => false
  end

  create_table "lessons", :id => false, :force => true do |t|
    t.column "lessonId",             :integer,                                :null => false
    t.column "subjectCode",          :string,  :limit => 10,  :default => "", :null => false
    t.column "lessonType",           :string,  :limit => 0,   :default => "", :null => false
    t.column "noOfLesson",           :integer, :limit => 2,                   :null => false
    t.column "frequency",            :string,  :limit => 0,   :default => "", :null => false
    t.column "lessonGroupsAssigned", :string,  :limit => 300, :default => ""
    t.column "possibleVenues",       :string,  :limit => 300, :default => ""
  end

  add_index "lessons", ["subjectCode"], :name => "subjectCode"

  create_table "logins", :id => false, :force => true do |t|
    t.column "userId",   :integer, :limit => 10,                 :null => false
    t.column "password", :string,  :limit => 50, :default => "", :null => false
    t.column "accType",  :string,  :limit => 10, :default => "", :null => false
    t.column "email",    :string,  :limit => 50, :default => "", :null => false
    t.column "userName", :string,  :limit => 50, :default => "", :null => false
  end

  create_table "reference_subjects", :id => false, :force => true do |t|
    t.column "subjectCode", :string,  :limit => 10,  :default => "", :null => false
    t.column "subjectName", :string,  :limit => 50,  :default => "", :null => false
    t.column "yearOfStudy", :string,  :limit => 10,  :default => "", :null => false
    t.column "discipline",  :string,  :limit => 50,  :default => "", :null => false
    t.column "acad_unit",   :integer, :limit => 2,                   :null => false
    t.column "cohort_size", :integer, :limit => 4,                   :null => false
    t.column "remarks",     :string,  :limit => 150, :default => ""
  end

  create_table "shared_subject_codes", :id => false, :force => true do |t|
    t.column "sharedSubId",        :integer,                                :null => false
    t.column "sharedType",         :string,  :limit => 20,  :default => "", :null => false
    t.column "sharedSubjectCodes", :string,  :limit => 150, :default => "", :null => false
    t.column "remarks",            :string,  :limit => 150, :default => ""
    t.column "sharedSubjectName",  :string,  :limit => 45,  :default => "", :null => false
  end

  create_table "slot_allocations", :id => false, :force => true do |t|
    t.column "allocationId",      :integer,                                :null => false
    t.column "lessonId",          :integer,                                :null => false
    t.column "groupId",           :integer,                                :null => false
    t.column "venueName",         :string,  :limit => 30,  :default => "", :null => false
    t.column "timeSlotId",        :integer, :limit => 2,                   :null => false
    t.column "alloc_lesson_freq", :string,  :limit => 0,   :default => "", :null => false
    t.column "lessonWeek",        :string,  :limit => 150, :default => "", :null => false
  end

  add_index "slot_allocations", ["lessonId"], :name => "lessonId"
  add_index "slot_allocations", ["groupId"], :name => "groupId"
  add_index "slot_allocations", ["venueName"], :name => "venueName"
  add_index "slot_allocations", ["timeSlotId"], :name => "timeSlotId"

  create_table "staff_assignments", :id => false, :force => true do |t|
    t.column "assignId",        :integer,                                :null => false
    t.column "groupId",         :integer,                                :null => false
    t.column "lessonId",        :integer,                                :null => false
    t.column "staffId",         :integer,                :default => 0,  :null => false
    t.column "teachLessonWeek", :string,  :limit => 150, :default => "", :null => false
  end

  add_index "staff_assignments", ["groupId"], :name => "groupId"
  add_index "staff_assignments", ["lessonId"], :name => "lessonId"
  add_index "staff_assignments", ["staffId"], :name => "staffId"

  create_table "staffs", :id => false, :force => true do |t|
    t.column "staffId",         :integer,                                :null => false
    t.column "staffName",       :string,  :limit => 50,  :default => "", :null => false
    t.column "division",        :string,  :limit => 50,  :default => ""
    t.column "school",          :string,  :limit => 3,   :default => ""
    t.column "designation",     :string,  :limit => 20,  :default => ""
    t.column "roomNo",          :string,  :limit => 15,  :default => ""
    t.column "extNo",           :string,  :limit => 4,   :default => ""
    t.column "email",           :string,  :limit => 50,  :default => ""
    t.column "subjectAssigned", :string,  :limit => 150, :default => ""
    t.column "remarks",         :string,  :limit => 150, :default => ""
  end

  create_table "subject_lists", :id => false, :force => true do |t|
    t.column "subjectListId",   :integer,                               :null => false
    t.column "subjectListName", :string,  :limit => 30, :default => "", :null => false
    t.column "subjectCode",     :string,  :limit => 10, :default => "", :null => false
  end

  add_index "subject_lists", ["subjectCode"], :name => "subjectCode"

  create_table "subjects", :id => false, :force => true do |t|
    t.column "subjectCode", :string,  :limit => 10,  :default => "", :null => false
    t.column "subjectName", :string,  :limit => 50,  :default => "", :null => false
    t.column "yearOfStudy", :string,  :limit => 10,  :default => "", :null => false
    t.column "discipline",  :string,  :limit => 50,  :default => "", :null => false
    t.column "acad_unit",   :integer, :limit => 2,                   :null => false
    t.column "cohort_size", :integer, :limit => 4,                   :null => false
    t.column "remarks",     :string,  :limit => 150, :default => ""
  end

  create_table "time_slots", :id => false, :force => true do |t|
    t.column "timeSlotId", :integer, :limit => 2,                  :null => false
    t.column "startTime",  :time,                                  :null => false
    t.column "endTime",    :time,                                  :null => false
    t.column "dayOfWeek",  :string,  :limit => 10, :default => "", :null => false
  end

  create_table "venues", :id => false, :force => true do |t|
    t.column "venueName", :string,  :limit => 30,  :default => "", :null => false
    t.column "venueType", :string,  :limit => 0,   :default => "", :null => false
    t.column "capacity",  :integer, :limit => 3,                   :null => false
    t.column "remarks",   :string,  :limit => 150, :default => ""
  end

end
